#!/usr/bin/env python3

# A sample training component that trains a simple scikit-learn decision tree model.
# This implementation works in File mode and makes no assumptions about the input file names.
# Input is specified as CSV with a data point in each row and the labels in the first column.

if __name__ == '__main__':
    
    print("in train")
    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)
